name: .NET CI/CD Pipeline

on:
  push:
    branches: [ "master" ]   # Only deploy from main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      #- name: Run tests
      #  run: dotnet test --no-build --verbosity normal

      - name: Publish project
        run: dotnet publish GravyFoodsApi.csproj -c Release -o ./publish/
      
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: /uniposapi.goooget.com   # e.g. /public_html or /var/www/myapp
